baseURL = 'https://shubhamalloc.github.io/'
languageCode = 'en-us'
title = 'shubham shah'
theme = "archie"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate = 4

[params]
# favicon = "https://img.icons8.com/officel/16/000000/chevron-right.png"
# og_image = "https://raw.githubusercontent.com/athul/archie/master/images/archie-dark.png"
#mode = "auto"
mode = "toggle"
useCDN = false
subtitle = ""
description = "personal website of shubham shah"
enableGitInfo = true
mathjax = true # enable MathJax support
katex = true # enable KaTeX support

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/shubhxms"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/shubhxms/"


[[menu.main]]
name = "about"
url = "/"
weight = 1

[[menu.main]]
name = "shelf"
url = "/shelf"
weight = 2

[[menu.main]]
name = "notes"
url = "/notes"
weight = 3

[[menu.main]]
name = "craft"
url = "/craft"
weight = 4

[[menu.main]]
name = "stream"
url = "/stream"
weight = 5


[permalinks]
  pages = '/:title'

[markup.goldmark.renderer]
unsafe= true

[outputFormats]
[outputFormats.data]
  mediaType = "text/html"
  isHTML = true

[outputs]
home = ["HTML", "data"]
